version: '3.8'

services:
  # Serviço do Banco de Dados (PostgreSQL)
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todos
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d todos"]
      interval: 5s
      timeout: 3s
      retries: 10

  # Serviço Redis (Cache)
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  # Serviço do Backend (API Node.js)
  backend:
    build: ./backend
    environment:
      NODE_ENV: development
      
      # --- JWT (CONFIGURAÇÃO FINAL) ---
      JWT_SECRET: key007

      # --- Banco de Dados ---
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: todos
      PORT: 3000

      # --- Redis (Cache) ---
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # --- Supabase (Storage) ---
      SUPABASE_URL: https://gzqtrkzssqednkuwqlct.supabase.co
      SUPABASE_ANON_KEY: sb_publishable_VT7Bcjy237XpBpbRC-cq5Q_NdpasdMS
      SUPABASE_SERVICE_ROLE_KEY: "${SUPABASE_SERVICE_ROLE_KEY:-}"
      SUPABASE_BUCKET: fotos

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # Serviço do Frontend (Nginx + React/Vite)
  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: https://gzqtrkzssqednkuwqlct.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_VT7Bcjy237XpBpbRC-cq5Q_NdpasdMS
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
  redisdata: