version: '3.8'

services:
  # -------------------------------------------------------
  # POSTGRES (Banco de Dados)
  # -------------------------------------------------------
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres       
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 5s
      timeout: 3s
      retries: 10

  # -------------------------------------------------------
  # REDIS (Cache)
  # -------------------------------------------------------
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redisdata:/data

  # -------------------------------------------------------
  # BACKEND (Node.js)
  # -------------------------------------------------------
  backend:
    build: ./backend
    environment:
      NODE_ENV: development

      # --- Porta interna do backend ---
      PORT: 3000

      # ---------------------------------------------------
      # JWT (obrigatório para autenticação bcrypt + JWT)
      # ---------------------------------------------------
      JWT_SECRET: "key007"

      # ---------------------------------------------------
      # Banco de Dados (ORM Sequelize)
      # ---------------------------------------------------
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: postgres

      # ---------------------------------------------------
      # Redis
      # ---------------------------------------------------
      REDIS_HOST: redis
      REDIS_PORT: 6379

      # ---------------------------------------------------
      # Supabase (Storage)
      # ---------------------------------------------------
      SUPABASE_URL: https://gzqtrkzssqednkuwqlct.supabase.co
      SUPABASE_BUCKET: fotos
      
      # Chave de autenticação usada pelo backend para upload
      SUPABASE_SERVICE_ROLE_KEY: "sb_secret_Gckzdobj1V-YEfcdp_b9gQ_HMx5VTpq"
      SUPABASE_ANON_KEY: sb_publishable_VT7Bcjy237XpBpbRC-cq5Q_NdpasdMS

    ports:
      - "3000:3000"

    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  # -------------------------------------------------------
  # FRONTEND (Nginx + Vite/React)
  # -------------------------------------------------------
  frontend:
    build:
      context: ./frontend
      args:
        VITE_SUPABASE_URL: https://gzqtrkzssqednkuwqlct.supabase.co
        VITE_SUPABASE_ANON_KEY: sb_publishable_VT7Bcjy237XpBpbRC-cq5Q_NdpasdMS
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  pgdata:
  redisdata:
